### ISSUE TITLE
Two dialogs when use Ctrl+O

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#11]
Select some text and hit Ctrl+O to insert a link to another topic. Two dialogs appear: an Open dialog (Ace Editor's?) and the Insert Bookmark dialog.

**Comment by RickStrahl** [comment]
Yes, that's been changed to Alt-O. Ctrl-O unfortunately has a browser shortcut that overrides key click events so that dialog pops up. Ctrl key trapping in the editor is tricky as the browser doesn't forward those to the host container - I actually capture the ctrl keys and then forward them explicitly to VFP o handle. Alt combos just work though. Ctrl-K still works via forwarding but Ctrl-O has the browser dialog 

FWIW, there is another related issue that has not been resolved at this point - focus. When the dialogs pop up I can't get them focused. The browser is not releasing focus until some sort of UI event happens out side for the editor (moving the mouse does it). This is annoying but unfortunately I've not been able to work around this including delayed focus resets etc. Unfortunately it seems some of these quirks I'm just going to have to live with in Help Builder - the price to pay for the new editor I suppose.

**Comment by DougHennig** [comment]
Re: focus. I ran into a similar issue years ago and my solution was inelegant yet effective :) -- I used the VFP MOUSE command to force the mouse to move one pixel, used DOEVENTS FORCE to force Windows to see it, MOUSE to move it back again, and another DOEVENTS FORCE.
