### ISSUE TITLE
Search content feature

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#112]
Search topic in the side bar is nice but somewhat limited. I'd like to see a general search option added when deploying as HTML.

**Comment by RickStrahl** [comment]
For that to work you need a server side bit that can do the searching.

Actually there's something on my backlog that is a client and server side indexing engine. But it won't be super fast for initial search.

**Comment by RickStrahl** [comment]
So good news: I've added an index search to Help Builder using [lunr.js](https://lunrjs.com/), which is simple way to build up a search index on the fly in the browser.

You can now choose between the old default implementation that searches topic headers, or the new Detailed mode which searces topic headers, keywords, ids and 512 chars of the content:

![image](https://user-images.githubusercontent.com/1374013/102727761-da1c1580-42cb-11eb-9f99-17d0ad2bc4d1.png)

Lunr is true indexed and somewhat basic weighted search meaning it can match multiple terms and rank them based on number of occurrances, similarity and where in the document the match occurs. you can also use wild cards.

It works but in playing around with this I'm not seeing much improved search results between the simpler title only search.

Made some additional changes:

* Search results no longer display as a tree but build a new flat list (like the Application)  
This removes a lot of clutter because the tree display required seeing all parent topics which could often mean most of topics were visible
* The highlight now is sticky on reloads and active topic is highlighted more clearly

![image](https://user-images.githubusercontent.com/1374013/102727896-c45b2000-42cc-11eb-8995-1ede4270b962.png)

Note the existing selected topic stays activated until you change it.

Overall that part actually makes the search much more usable as it drastically reduces the clutter.

It'll be in the next update, hopefully next week.

**Comment by RickStrahl** [comment]
It's running here now so you can check it out:

https://markdownmonster.west-wind.com/docs/

**Comment by rikaye** [comment]
Thanks, Rick! I checked it out and it looks like it will be a good update.

**Comment by RickStrahl** [comment]
More info on the search feature in the updated documentation:

[Searching in the Table of Contents](https://helpbuilder.west-wind.com/docs/_5xt158kv5.htm)
