### ISSUE TITLE
Cannot Import CHM or HHC

### ISSUE THREAD

**Issue by ghost** [RickStrahl/HelpBuilderReleases#29]
We have a hosed HBP. We didn't make backups. We know that this is bad and we will not do it again. In an effort to not start over, we are trying to use the Import feature. Under the latest 5.0 Beta I get a file is in use error after I click the import button. It takes a while though so I know that some processing is going on.  This is a new error for 5.0.  Under the older 4.x, we still got an error but it was a class not registered error. We really would like to get our help project back, please. :-)

Steps:
1. Load Help Builder
2. Tools - Import
3. Select a CHM.
4. Pick a output destination.
5. Turn off Remove Original, Imported HTML files
5. Click Import.

Observed:An extracting topics WAIT WINDOW and then File is in Use. When I click cancel, everything shuts down. If I click Ignore, I eventually get a OLE error: The object invoked has disconnected from its clients. In the background, IE is open viewing <help file name>.importhhc.htm. This document is just a series of bullets on 3 different levels. 

Expected: Hopefully a new Help Builder Project.

**Comment by RickStrahl** [comment]
@ToniFeltman the import from CHM feature was never perfect as it can only import the HTML as is, not the real structure. In 5.0 this feature has been removed as it set expectations too high of what can be expected from topics. I might add it back since now Help Builder does support native HTML topics, but at the moment that's on hold.

I suppose you've tried recovering the hbp file, right? Usually you can salvage DBF tables or at least part of it with various recovery tools.

**Comment by ghost** [comment]
Good Morning Rick! I tried this in the 5.0.150 beta. Did you remove it int he next update? 

I would love to try to recover the HBP file except that it is not corrupted like that. :-) Our tech writer is not sure what he did but he managed to remove all of the topics from the project (yes I checked for deleted records). Then he closed and reopened the project which cleared the _recover file too.  The files sizes are like 1 and 2K.

We have all of the HTML that is generated when building a help file and Word Doc.  Can any of that be used to rebuild the structure? If there is nothing built in, I suppose I can write something to parse the HHC or the Table of Contents HTML and stuff it into the table. But, I am not sure that this would be faster than PJ just entering them manually. 

Thanks for you help!

Toni-

**Comment by RickStrahl** [comment]
Let me take a look today and see what is actually happening with that code. There's no reason that the code that is there shouldn't be working in the current version. There are a handful of things that got disabled because they broke, but the fixes are probably pretty minor.

If you do go the route of importing and the stock import doesn't work there's a plugin that I built originally that does this as well. You can use the source code for that. I think Andrew McNeal started it and I reworked it a bit for better HTML parsing of the content etc.

**Comment by RickStrahl** [comment]
Toni, the good news is I've fixed the import and updated it so it actually works a little cleaner now. The new version supports raw HTML content so imported HTML works easier as is. I tried a handful of help files and it works rather well.

The bad news is that I'm in the middle of some major updates for the templates that doesn't let me push the new changes out to you just now. It's going to be a few days until I can get the templates all line up.

**Comment by ghost** [comment]
Rick, you are a gem! A few days is fine. We don't need to put out an update to our client for a little while. I know that I have said this a few times.... I owe you. :-)

**Comment by RickStrahl** [comment]
Toni - the new build that includes the fixed importing functionality for CHM files is now up. Give that one a shot and let me know what you find.

Note: You will need to update your templates as this version includes a completely new set of templates.

**Comment by RickStrahl** [comment]
Close for now, since there's no further discussion.
