### ISSUE TITLE
Different rendering for Markdown and HelpBuilder

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#34]
If a topic uses HelpBuilder for markup, paragraphs are being generated as:

text&lt;p&gt;more text&lt;p&gt;

For Markdown, it's like this:

&lt;p&gt;text&lt;/p&gt;&lt;p&gt;more text&lt;/p&gt;

As a result, topics using HelpBuilder don't have the proper spacing between paragraphs, which forces me to change every topic to Markdown (unless this is fixed).

**Comment by RickStrahl** [comment]
Yeah - the old syntax isn't actually fully HTML compliant - it uses only opening tags and no closing tags. The DOM is smart enough to turn the unclosed `<p>` tags into proper paragraphs with closing tags, but the first paragraph doesn't because there's no opening `<p>`.

Part of the problem is the way BootStrap defines the <p> tag behavior so it behaves differently than what we had in the old version. The new styling however is proper so the bootstrap styling will stay intact.

So I've added a change that adds a leading `<p>` tag for all .FormatHtml() calls in Help Builder mode. The leading <p> forces the first paragraph into a full paragraph, which then gives the same behavior as the Markdown edited text.

In brief testing it looks like this will address the problem but check out your rendering in the next build in  .208.

**Comment by DougHennig** [comment]
Yup, looks better now. Thanks.
