### ISSUE TITLE
[Import of chm] Links to anchors on a page are imported as full topics

### ISSUE THREAD

**Issue by FransBouma** [RickStrahl/HelpBuilderReleases#39]
Hi,

If you have links to anchors in a page, the page is imported multiple times and the topics in the ToC become full links.

An example is the `Concepts -> Database First and Model First` page in the CHM I gave you. It's a single page (`Concepts\DatabaseFirstModelFirst.htm`) and the ToC has two sub elements below that node: Database first (which links to `Concepts\DatabaseFirstModelFirst.htm#dbfirst`) and Model first (which links to `Concepts\DatabaseFirstModelFirst.htm#modelfirst`). 

If this chm is imported, the ToC in Helpbuilder contains the node `Concepts` which has as child node `Database First and Model First` (which contains the full page content of `Concepts\DatabaseFirstModelFirst.htm`) that node contains 2 subnodes, Database First and Model First which too both contain the full content of `Concepts\DatabaseFirstModelFirst.htm`. 

Not sure if this is supported though. The 2 child nodes `Database First` and `Model first` are relative links to sub headers in the full page `Concepts\DatabaseFirstModelFirst.htm`, so the content is more discoverable through the ToC.

**Comment by RickStrahl** [comment]
Hmmm... yes I see that's a problem, but I don't think I'll fix this because frankly that's such an edge case. This comes back to the point of having top level topics with anchors which is just not supported by Help Builder.

On the upside for you though - this actually gives you all the TOC topics you had with the right names and some duplicated content that you can clear out which is actually easier than Copy/Paste...
