### ISSUE TITLE
Web Preview showing wrong project

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#41]
I have two projects, both with a filename of SFQuery.hbp (one for our VFP version, one for the .NET version). After restarting my machine, I opened the .NET one in wwHelp and chose Open HTML Project in Web Browser (generated the HTML files previously). The table of contents displayed is for the VFP one. However, the content is from the .NET one. For example, both projects have a topic _0380pvt6u (because a couple of years ago I started with the VFP project and copied it to a new folder to create the .NET version) so clicking on that topic displays the correct content for the .NET project. Clicking on topics that don't exist in the .NET version does nothing.

**Comment by RickStrahl** [comment]
The preview uses a single Web site base url/ipaddress/port so as you browse to a project the base URL for different projects is the same, even though underneath the Web site is pointing to a new location.

The problem is browser caching. if you Reload the Page (F5) you'll get the correct page. Note you may also have to recompile the project (or 'upload' the current topic and abort to force an individual topic to update).

Unfortuantely there's nothing I can do about browser caching and I also can't use different IP addresses because the IP addresses need to be unblocked to work on the local machine in non-admin mode.

**Comment by DougHennig** [comment]
Doh! You're right -- it was just a browser caching issue.
