### ISSUE TITLE
Error installing version 5.0.222

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#43]
Error message:

West Wind HTML Help Builder
File installation failed.
The installation will be cancelled.

In Operation progres
Installing files
C:\Program Files (x86)\West Wind Html Help Builder\templates\msword\msword.txt
17%

Tested on more PCs 32 or 64 bit Windows10.
Version 5.0.221 is without problem.

**Comment by RickStrahl** [comment]
Hmmm... that's not a file we install.

I also tried doing a clean install and an update install and neither of them failed for me. 

I think what might be the issue is that I changed the GUID for the installer project so the install is separate from the 4.x installation. So it's possible there's some quirk trying to uninstall the old version. See if you can run an uninstall explicitly first, then reinstall.

I'll have another update later today, maybe recheck with a post .222 version and see if there's still a problem.

**Comment by zdenekkrejci** [comment]
I've done this procedure:
1. uninstall previous version 5.0.221.
2. Delete rest of directory C:\Program Files (x86)\West Wind Html Help Builder\
   (3 files unable to delete (fontawesome-webfont.ttf._rb, 
  File  C:\Program Files (x86)\West Wind Html Help Builder\templates\msword\msword.tid
 doesn't exist.
3. run HelpBuilderSetup.exe
4. messagebox:

West Wind HTML Help Builder
File installation failed.
The installation will be cancelled.
OK   

Under the messagebox is dialog installation progress with label 
Installing files 
C:\Program Files (x86)\West Wind Html Help Builder\templates\msword\msword.tid
1. file 
   C:\Program Files (x86)\West Wind Html Help Builder\templates\msword\msword.tid
   exists with length 1byte, date 02.202.2016 9:01:10

I think the error is in the next file.
May be 
C:\Program Files (x86)\West Wind Html Help Builder\templates\msword\scripts\fontawesome\fonts\fontawesome-webfont.ttf._rb
which cannot be deleted.

Installation of the previous version 5.0.221 wihout problems.

**Comment by RickStrahl** [comment]
Did this resolve with later builds? .223 or .224?

**Comment by zdenekkrejci** [comment]
Yes, in download .224, after install shows .223 in About dialog.
Inslallation works.

Thank you
