### ISSUE TITLE
Table in mardown

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#45]
Insert links and images in Markdown syntax doesn't work within HTML tags.
If you want to put link or image into the html table, you have to use HTML syntax.
This causes some disunity.
Would it be possible to write HTML table in Markdown syntax?

For example, according to Github  Markdown implementation.
[https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**Comment by RickStrahl** [comment]
The Markdown component we use doesn't support tables yet although I believe it's on the list for additions that are coming. Tables aren't part of the Markdown spec per se and [CommonMark.NET](https://github.com/Knagis/CommonMark.NET) sticks close to the spec.

Help Builder has a few custom extensions (like code and links) but those are relatively easy to implement. Table support with nested markdown inside of it is something that has to be handled at the parser level unfortunately because there's a lot that has to happen to make this work.

I'm going to close this for now - but will keep this in mind for future support.

**Comment by RickStrahl** [comment]
Pipe and Grid Tables are now supported.
