### ISSUE TITLE
Change combobox value when convert to Markdown

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#5]
If you choose the Convert to Markdown function, change the value of the text type combobox from "Help Builder" to "Markdown".

**Comment by RickStrahl** [comment]
You mean the button on the toolbar? 

I was debating about this and decided to keep these two completely separate. The problem is that the toolbar has no way of knowing whether a topic has already been converted and you don't want to convert an already converted topic. It's not a big deal if you do but there might be a few things that get inadvertantly converted by a second conversion.

Steps right now to convert are:
- Switch to Markdown in the Combo
- Select the topic - then click the Markdown button to convert

I suppose it would make sense to click the Markdown button and then change the Viewmode for the topic though.

**Comment by DougHennig** [comment]
The latter is what I meant: when you click the button, change the viewmode to Markdown. I see you made that change already so I'll close this.
