### ISSUE TITLE
Build process replaces body and/or topic title

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#51]
I've seen this happen numerous times but never when I try specifically to reproduce it (of course). Here's what I'm seeing:
- Sometimes after a build, I get the "Do you want to update all cross links" dialog showing that it thinks I changed the topic title, which I didn't. When I look at the generated help, it's used the current topic title as the project name. When I look in the HBP file as a table, I see the TOPIC and BODY of the INDEX record have been replaced with the current topic.
- Today I saw something different. I edited topic A, then edited topic B and clicked the Build Output button without saving the topic or clicking anything after moving the mouse out of the ACE editor. After building a CHM, I went back to topic A and it now has the body of topic B. This I can reproduce as you can see in the attached video: after building, the body of the dbo.Customers topic is replaced with the body of the yada topic.
  [build.zip](https://github.com/RickStrahl/HelpBuilderReleases/files/186952/build.zip)

**Comment by RickStrahl** [comment]
Yes I've run into this as well. It's caused by the edit control getting focus and then updating the topic. If the record pointer has moved this can cause corruption by writing the topic content into the wrong topic. Most often this happens during uploads or other wizard tasks to bring up new windows and it seems like it always clobbers the Index topic.

I have mitigated this to some degree with the dialog that catches the topic change but I still see it occasionally getting past even that.
