### ISSUE TITLE
Issues changing Template Scheme

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#7]
This doesn't happen all the time, but sometimes when I choose Select Template Scheme and select a different template, I get a "current template scheme has no name" dialog. If I enter a name (the same name as the scheme I chose) and click OK, I get a "File <path>\templates*.\* does not exist" error.

**Comment by RickStrahl** [comment]
I think this is fixed in the latest release that's online. The early beta I sent you definitely had issues with the template switching. Can you retry with any build post 5.0.35 (it's not up there but I plan on pushing another one later today).

**Comment by DougHennig** [comment]
Same issue in 5.0.51.

**Comment by RickStrahl** [comment]
Hmmm... I can't repro this. I've tried selecting a new theme 20-30 times with different views active but I can't make it fail. I've seen this behavior before, but I've never been able to track down a reliable repro to actually fix it.

Can you check the template you are selecting? Make sure there is a `ThemeName.tid` file in the folder for the actual template which is what gets the name of the theme.

Another thing to try: Try creating a new project and see if you see the same behavior. It's possible it might have to do with the old template themes (although it shouldn't).

**Comment by DougHennig** [comment]
I was able to reproduce this with a new project. Steps:
- Create a new project
- Select the Scripts template
- Error "File 'c:\users\dhennig\desktop\test2\templates\scripts*.*' does not exist." occurs; choose Ignore
- Select any template (note Scripts no longer appears in the combobox)
- The "current template scheme has no name" dialog appears.

As for an existing project, many of the template folders don't have a TID file (this project was started more than 10 years ago so it's really old). Selecting one of those templates definitely causes a problem. Perhaps the template combobox should only list templates that have a TID file. Also, perhaps when a project is open, Help Builder could detect that it's an older project and offer to update the templates to the current ones. I know there's a button in the Options dialog to do that but many people may not find that.

**Comment by RickStrahl** [comment]
Thanks Doug! Elusive bug indeed. It's only on topic clicks and only if the link is embedded a certain way. Should now work (post 5.0.61 when out).

**Comment by RickStrahl** [comment]
Hmmm... what version are you seeing the SCRIPTS template on? That should no longer be showing up - it's filtered out, but I would definitely see that as a problem since that folder will have none of the dependencies :-)  that was definitely a bug.

Old theme folders should probably work too. The goal is to have old templates work - they should because each theme holds everything it needs in terms of dependencies (scripts/css and HTML templates). They may require some tweaking but they should work. 

I'll put this on my list, but it'll be low priority for now. I'd like to get the core templates and structure working before I worry about old templates :-)

If you see failures switching between the new templates do let me know. I'll update this issue as I have more info.

**Comment by DougHennig** [comment]
SCRIPTS no longer appears in 5.0.68.

**Comment by RickStrahl** [comment]
Added explicit creation of .TID file and killing other .TID files when a theme is selected. This should ensure there's always a TID file in place. Also consolidated theme switching code so now both the simple Theme swtiching list and the Modify Theme form use the same code.
