### ISSUE TITLE
No more search?

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#70]
The "Add search option" setting in the Generate HTML Help dialog is gone and while search.aspx still exists, it isn't referenced anywhere. How do we get the search feature back?

**Comment by RickStrahl** [comment]
It's been removed because it no longer really fits with the new layout and has always been a problem because it's very slow and requires IIS to run. 

Search now works through the search box that looks at topic titles in the tree only. It's more limited for sure as it doesn't search topic content but it also encourages you to create topic titles that identify content clearly :-)

Sorry.

**Comment by DougHennig** [comment]
Fair enough.

**Comment by RickStrahl** [comment]
Does the topic search not work well enough for you? I find that it's a much more usable experience even though there are definitely some scenarios where full text search would find more content.

The trick is to not create massive topics, but break those out into separate topics in a subtree perhaps. Switching to search like this has made me change how I write topics for sure :-)

**Comment by DougHennig** [comment]
I actually don't use it myself: I search the HBP file in Help Builder. I was thinking of customers who might use it, but then realized most of our customers likely use the CHM file, which does have search. The reason we have the online web help is so we can send a customer directly to a relevant help topic without having to tell them to naviagate to topic X in the CHM. So, in hindsight, I'm not sure anyone would use a full-text search option anyway.
