### ISSUE TITLE
Markdown not supported in HTML tables

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#74]
I find that Markdown table syntax is harder to use than HTML syntax: I spend a lot of time getting the columns right using pipes and dashes. However, Markdown syntax for links isn't supported in HTML tables: I have to use the older "<%= TopicLink([my text],[_0OW0Y4DGO]) %>" syntax instead.

**Comment by RickStrahl** [comment]
Yeah this needs a table editor like Markdown Monster. If you have a complex table maybe for now copy the code into MM then use the table editor there. Grid tables support embedded Markdown. Pipe tables do too but they are more limited.

Antoher thing to remember about grid and pipe tables - the pipes and dashes don't have to line up. Only the number of connectors have to match to create a valid table.

**Comment by DougHennig** [comment]
I'll give that a try, thanks.

**Comment by RickStrahl** [comment]
Hmmm... this works for me:

![image](https://user-images.githubusercontent.com/1374013/38962652-ff4bafec-4309-11e8-9b89-3d2e10cae44a.png)

Note I adjusted the CSS so that all `.detailtable` rendering uses `table` in general to get the styling you see here. I thought this was already done, but apparently didn't make it into the final build.

**Comment by DougHennig** [comment]
Yeah, it works in a Markdown table but not an HTML table:

![link](https://user-images.githubusercontent.com/12052409/39010888-8bf5486a-43d5-11e8-80f7-63835eabd92a.png)

**Comment by RickStrahl** [comment]
Yeah you can't use markdown inside of HTML blocks. Once you're inside of an HTML block the Markdown parser treats it as markdown, so that just simply won't work.

You can look into using [Grid tables](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/GridTableSpecs.md) which have a little more control than pipe tables (similar).
