### ISSUE TITLE
Build output error

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#84]
#### Error Message:
Neznámý člen RADHELP10.

#### Module: 
PROCEDURE WIZBUILDOUTPUT.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP_UI.VCT

#### Line:
12

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | c:\program files (x86)\west wind html help builder\wwhelpmain.prg (306) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (390) |
   		THISFORM.RunWizard("wizBuildOutput")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (28) |
   loBuild = CREATEOBJECT(lcWizClass,THIS)
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.init | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (12) |
      thisform.pgfSteps.PagStep1.optCompiler.radHelp10.Enabled = .f.
----
6. errors.fxp | ON...  | c:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by yalangriver** [comment]
@RickStrahl - FWIW, I'm getting the same error. Here's my dump:

#### Error Message:
Unknown member RADHELP10.


#### Error Number: 1925

#### Module: 
PROCEDURE WIZBUILDOUTPUT.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP_UI.VCT

#### Line:
12

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (306) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (390) |
   		THISFORM.RunWizard("wizBuildOutput")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (28) |
   loBuild = CREATEOBJECT(lcWizClass,THIS)
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.init | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (12) |
      thisform.pgfSteps.PagStep1.optCompiler.radHelp10.Enabled = .f.
----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----


#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Can you take another look in 1.15.3 which I just sent up? If it still fails can you give me exact steps?

I think the problem that you see is a build error on my end - I don't see it. I updated the latest version today so let's make sure we're on the same version for the error if it's still there.
Thanks.

**Comment by yalangriver** [comment]
Sure – let me go check it now.

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by yalangriver** [comment]
Downloading it manually off the website. Going into the menu to check for an updated version gave me an error getting the version #.

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by yalangriver** [comment]
Still fails with the following:

#### Error Message:
Unknown member RADHELP10.


#### Error Number: 1925

#### Module:
PROCEDURE WIZBUILDOUTPUT.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP_UI.VCT

#### Line:
12

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (306) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (390) |
                                THISFORM.RunWizard("wizBuildOutput")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (28) |
   loBuild = CREATEOBJECT(lcWizClass,THIS)
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.init | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (12) |
      thisform.pgfSteps.PagStep1.optCompiler.radHelp10.Enabled = .f.
----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----


#### Window:
WWHELPFORM


Steps: Run WWHelp. Click on “I agree” (no paid version yet). Click on toolbar “Build Output” Blammo! (that’s a technical term).

Feel free to give me a holler on my cell at 425-301-1590 or set us up with a Zoom meeting or whatever if you want to follow along/debug on my machine.

yag

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by yalangriver** [comment]
@RickStrahl I did just notice something - if I go into Insert Bookmark, I show two <root> lines. See screencap:

![image](https://user-images.githubusercontent.com/13696864/54637374-83c6d680-4a56-11e9-988a-42a778383f89.png)

**Comment by RickStrahl** [comment]
@yalangriver where did you grab this from? The code you're running is not the latest version. The latest version embeds the version number into the error report  - your's does not. Chocolatey is uploaded but not available yet I think. Make sure you're running 5.15.3 from the download page or explicitly download 1.15.3 or later from Choco.

**Comment by RickStrahl** [comment]
As to the duplication that looks like a duplicated topic.

**Comment by yalangriver** [comment]
I got it from the website directly (clicked the download button).

As far as the dupe topic, I don't see it anywhere else in the project. That's the weird part.

I may create a new one and copy the text. Start over.

Get Outlook for Android

________________________________

**Comment by RickStrahl** [comment]
Does it say 1.15.3 on the start screen? 

The Dupe topic is strange - i looks like it's the root topic of the tree (no parent topic). You might have to go into the hbp file (Fox file) to see what's happening there. That's definitely not right and that might cause some problem down the line because it might randomly switch between these two. The thing to do would be to delete one of the two.

If you want you can privately send me the hbp file and its related files and I can take a look - might be useful to check and see what went wrong there.

**Comment by yalangriver** [comment]
![image](https://user-images.githubusercontent.com/13696864/54645578-6f8cd480-4a6a-11e9-8643-15846286fb07.png)

**Comment by RickStrahl** [comment]
Uoh... that's odd. That's not a valid release - I guess you must have gotten in there when I had an accidental build up there. Can you uninstall and reinstall?

Sorry about that... the version should be 1.15.3.

**Comment by RickStrahl** [comment]
Ok took a look at your file. The root duplication is a bug... it's showing the CONFIG topic which holds the project title. 

Fixing.

**Comment by yalangriver** [comment]
OK. I'll wait to download (got a meeting downtown this evening anyway). FYI, I downloaded from https://helpbuilder.west-wind.com/download.aspx - and the page still shows 5.16.0. 

![image](https://user-images.githubusercontent.com/13696864/54646234-74528800-4a6c-11e9-90b9-8cd135e46a84.png)

**Comment by yalangriver** [comment]
Hmm. Make that .3 :)

**Comment by RickStrahl** [comment]
Right. Sorry I thought it was .15.3 but it's 16.3. Your screenshot though showed 5.16.0.

**Comment by zdenekkrejci** [comment]
After uninstall and new install id now works.
Thank You.

**Comment by yalangriver** [comment]
FYI – I uninstalled and reinstalled – shows 5.16.3 now – but still get the same error.

yag

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by yalangriver** [comment]
@RickStrahl Even worse - I just created a totally new project, kept the default (IOW, did no changes), clicked Build Output and got the same error. Not sure where to go next.

**Comment by RickStrahl** [comment]
So what are you doing exactly and when does it blow up?

* Open the Build Dialog
* Select Build Help File?
* Next then Finish (or just Finish)?

Or does it blow up as you open the dialog. Same error as before (rad10 not defined?).

I can't duplicate that here with 5.16.3 with uninstall/reinstall.

**Comment by yalangriver** [comment]
1.  I go into WWHelp.
  2.  File/New/New Project.
  3.  Fill out the wizard.
  4.  Click Build Output on toolbar.
  5.  Error (rad10 not defined)

[cid:image001.png@01D4DF29.0A1CCDA0]

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by AntonijoSamarija** [comment]
It is very strange what happens to Alan.
I have tried to open a new project several times Build Help File and can not produce the same error.
Maybe there is something else that has nothing to do with Html Help builder.
Help Builder version is 5.16.3

**Comment by yalangriver** [comment]
Out of desperation I just checked and installed some updated firmware that was sitting in Windows Update. Restarted Windows. Still no joy.

Rick – if you want to do a webmeeting and debug on my machine, happy to set up a time.

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by RickStrahl** [comment]
Yeah I don't know either and I can't duplicate that. Alan, can you double check that the version shows 5.16.3 and not your original version? Maybe the uninstall/reinstall failed somehow?

The code that was blowing up is in the main EXE so if the version is correct it can't be an external dependency that's failing, but if that still fails with the right version I really have no idea what else it could be...

**Comment by yalangriver** [comment]
[cid:image001.png@01D4DF2F.56BDC000]
It says 5.16.3 ☹

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by RickStrahl** [comment]
Yag - send me an invite or ping me on Skype (@ rickstrahl) and we can take a look. But frankly if you are in fact running the right version and you still get that same error (not something else if you capture the bug message) then I don't know what could be causing that.

Anyway ping me. I'm at the MVP Summit so might not get back to you right away.

**Comment by AntonijoSamarija** [comment]
Uninstall with Revo Uninstaller or similar tool.

**Comment by RickStrahl** [comment]
Help Builder doesn't have anything tricky installed so I think a plain uninstall should work just fine. If you want to be thourough delete the `\program files (x86)\ West Wind Html Help Builder` folder after uninstall, then reinstall.

So what I can think of is this: THere were changes related to dependent DLLs which all got moved to the `\bin` folder. Maybe something didn't get removed and so using an old DLL, but I can't imagine why that would be a problem when you open that dialog, and I would think I'd see that here since I never did a manual folder clean here either.

Sorry for the hassle Alan...

**Comment by yalangriver** [comment]
Maybe this is a clue? I just uninstalled, made sure there was no help builder folder. Reinstalled.

I go to Help/About and it shows the version as 5.16.3
If I go to Help/Check for Helpbuilder Updates, I get “There’s been an error retrieving the version info”.

Just another bit of weirdness.

Yair Alan Griver
[justice-for-me-logo]<http://www.justiceforme.com/>
Bridging the Justice Gap
425.301.1590 (m)

Connect with Us:
Web<http://justiceforme.com/> | LinkedIn<https://www.linkedin.com/company/justiceformeco> | Facebook<https://www.facebook.com/JusticeForMeCo/> | Twitter<http://twitter.com/JusticeForMeCo> |Instagram<http://www.instagram.com/justiceformeco>

NOTICE TO RECIPIENT: This communication may contain confidential and privileged information protected by law. If you received this e-mail in error, please notify the sender immediately by reply e-mail and permanently delete this e-mail and any attachments without reading, forwarding or saving them. If you are not the intended recipient of this e-mail, you are prohibited from sharing, copying, or otherwise using its contents. Thank you.

**Comment by RickStrahl** [comment]
I've updated the executable one more time fixing the bookmark duplicate issues and also the version check. Those are now fixed.

As to the build crash issue - I don't think anything changed here. So if you still have an issue lets do a Skype or WebEx session. Contact me by email - I'm travelling today but I'm at the airport for 4 hours from now on a layover so that works. (@ RickStrahl on Skype)

**Comment by yalangriver** [comment]
The bookmark dupe issue and version check are fixed - I can confirm. Still getting the crash. I pinged you on Skype - in case you didn't get it, I'm yalangriver - ping me when you start your layover. I should be around.
