### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by bgauvey** [RickStrahl/HelpBuilderReleases#86]
#### Error Message:
Unknown member RADHELP10.

#### Module: 
PROCEDURE WIZBUILDOUTPUT.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP_UI.VCT

#### Line:
12

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (306) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (390) |
   		THISFORM.RunWizard("wizBuildOutput")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (28) |
   loBuild = CREATEOBJECT(lcWizClass,THIS)
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.init | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (12) |
      thisform.pgfSteps.PagStep1.optCompiler.radHelp10.Enabled = .f.
----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Thank you - we're tracking this one and I think it'll be fixed in the next update. For now the quick solution (I think is) to make sure you have HTML Help Workshop installed before you open that dialog.

It's related to the logic that displays this:

![image](https://user-images.githubusercontent.com/1374013/54846343-d8599400-4c98-11e9-828d-4fe765189445.png)

If you don't plan on building HTML Help (CHM) output  and only use HTML results then maybe hold off. I should have this update out sometime later today.

**Comment by RickStrahl** [comment]
1.15.5 is up - give it another try with that and please let us know if that worked (and close this issue). 
Thanks.
