### ISSUE TITLE
Create missing files at startup

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#91]
I use FoxBin2PRG (https://github.com/fdbozzo/foxbin2prg) to convert the HBP, FPT, and CDX files to their text equivalent (a DB2 file). The DB2 file is the only file in the repository because all of the other files can be generated by Help Builder. However, cloning a repository, converting the DB2 file back to the HBP file, and then opening it with Help Builder gives "file doesn't exist" errors.

So, the ER is to have Help Builder create any missing files at startup. The code is already there somewhere; it creates them when creating a new project.

**Comment by RickStrahl** [comment]
The problem here is `lookups.dbf/fpt`.  While I can create that file, you'll want to have that file in your repo because it contains potentially project specific adjustments to project types, custom icons and themes.

I think the simpler solution here is to also pack the `lookups.dbf` and fpt as part of your project conversion to text.

**Comment by DougHennig** [comment]
Fair enough
